---
- name: Deploy concourse ci
  hosts: app
  vars_files:
    - ["vars/main.yml"]
    - ["vars/credential.yml"]
  handlers:
    - name: restart concourse-ui
      service: name=concourse-ui state=restarted

  tasks:
    - name: Copy systemd config for concourse web
      template: src=templates/init-concourse-ui.j2 dest=/lib/systemd/system/concourse-ui.service
      notify:
        - restart concourse-ui
